FROM atlasml/ml-base

RUN sudo pip install xgboost==0.90 python-dotenv
RUN sudo pip install google-cloud google-cloud-bigquery google-cloud-automl google-cloud-storage google-cloud-logging
RUN sudo pip install google-api-python-client
